name: vlm_firewatch_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.3.0
  - torchvision=0.18.0
  - torchaudio=2.3.0
  - pip:
    - transformers
    - accelerate
    - einops
    - Pillow
    - bitsandbytes
    - timm
    - scikit-learn
    - ultralytics
    - numpy