name: vlm_firewatch_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - transformers
    - accelerate
    - einops
    - Pillow
    - bitsandbytes
    - timm
    - scikit-learn
    - ultralytics
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
    - onnx
    - tensorrt-cu12
    - pycuda